### PR TITLE
Basic performance tests

### PR DESCRIPTION
**Pull request by DixonDs**
The main purpose of these performance tests is not to compare SM performance with other containers (this is perfectly done in https://github.com/danielpalme/IocPerformance) but rather to have some baseline tests that could be used every time to check if certain code change improves performance or not.

For this purpose, there are three versions of SM used in the benchmarks - the latest 3.X.X version, the latest 4.X.X version and the current code. So every time, one wants to make experiments, he or she can just use two benchmarks - the latest stable version from NuGet with the version from sources. Currently, it can be done by adding some filter in `Program`, but with next version of BenchmarkDotNet, it could be done by definining certain categories (https://github.com/dotnet/BenchmarkDotNet/issues/248)

### CODE REVIEW

**Comment by jeremydmiller** [comment]
@DixonDs I got these in, but how do you run this? Could you add a rake task? I can't get it to get past the ilmerge stuff

**Comment by DixonDs** [comment]
@jeremydmiller  "src/StructureMap.Testing.Performance" is just a console app. Not sure if there any point to add it to the build process. What errors do you get?

**Comment by jeremydmiller** [comment]
@DixonDs I get this:

```
C:\code\structuremap\src\StructureMap.Testing.Performance>dotnet run StructureMap.Testing.Performance --configuration Release
C:\code\structuremap\src\packages\MSBuild.ILMerge.Task.1.0.5\build\MSBuild.ILMerge.Task.targets(87,5): error MSB4062: The "MSBuild.ILMerge.Task" task could not be loaded from the assembly C:\code\structuremap\src\packages\MSBuild.ILMerge.Task.1.0.5\build\..\tools\MSBuild.ILMerge.Task.dll. Could not load file or assembly 'Microsoft.Build.Utilities.v4.0, Version=4.0.0.0, Culture=neutral, Public
C:\code\structuremap\src\packages\MSBuild.ILMerge.Task.1.0.5\build\MSBuild.ILMerge.Task.targets(87,5): error MSB4062: The "MSBuild.ILMerge.Task" task could not be loaded from the assembly C:\code\structuremap\src\packages\MSBuild.ILMerge.Task.1.0.5\build\..\tools\MSBuild.ILMerge.Task.dll. Could not load file or assembly 'Microsoft.Build.Utilities.v4.0, Version=4.0.0.0, Culture=neutral, Public

The build failed. Please fix the build errors and run again.
```

**Comment by DixonDs** [comment]
@jeremydmiller ah, it is a full .Net Framework console app, you can't really run it from .Net Core. I think ILMerge was one of the reasons why I made it .Net Framework only.

**Comment by jeremydmiller** [comment]
Ah, okay, that makes sense

**Pull request merged**
