### PR TITLE
Make Container store child containers in a thread safe manner

### PR DESCRIPTION
**Pull request by Mike737377**
This should fix issue #440 

Unfortunately I can't build it on my machine and test it as it is complaining about VS tooling issues.

### CODE REVIEW

**Comment by Mike737377** [comment]
Would you prefer a lock around adding to the list instead of using a ConcurrentBag?

**Comment by jeremydmiller** [comment]
@Mike737377 I think that ConcurrentBag is fine, and thank you for doing this. The only thing I'd ask maybe is a smoke test that tries to create lots of child containers in concurrent threads w/o failure.

More importantly, what are you doing with Child Containers that even brings this problem out?

**Comment by Mike737377** [comment]
@jeremydmiller I was spinning up a particular service endpoint which required a new instance each time instead of a standard shared one. It was occurring about ~5% of the time when initially putting the application under load (approx 250+ requests per second in parallel over 10 threads into an NServiceKit service). I've rearchitected so I don't need to create child containers anymore in that section. 

I'll create a test for it tomorrow. Which hopefully shouldn't be too hard to replicate it.

**Comment by jeremydmiller** [comment]
@Mike737377 Not trying to put any pressure on you, but I'll release a 4.1 nuget w/ some other fixes as soon as your PR is in. If you can't get to the crazy smoke test, just let me know and I'll add that.

**Comment by Mike737377** [comment]
@jeremydmiller stress test added

**Pull request merged**
