### PR TITLE
Fix for multithread Dictionary access issue causing 100% CPU usage

### PR DESCRIPTION
**Pull request by cspwizard**

### CODE REVIEW

**Comment by jeremydmiller** [comment]
@cspwizard Where was it using LightweightCache anywhere where it would have been under a multi-threading load? I'd rather change those places to use ConcurrentDictionary instead of forcing everything to be ConcurrentDictionary by changing LightweightCache.

**Comment by cspwizard** [comment]
Hi @jeremydmiller.

Here is some stack trace from dump that we had due to this issue: 

```csharp

0000000601c2db60 00007fff6363206b System.Collections.Generic.Dictionary`2[[System.__Canon, mscorlib],[System.__Canon, mscorlib]].Insert(System.__Canon, System.__Canon, Boolean)
0000000601c2dc00 00007fff65ede93e StructureMap.Util.LightweightCache`2[[System.__Canon, mscorlib],[System.__Canon, mscorlib]].get_Item(System.__Canon)
0000000601c2dc60 00007fff6a716e3c StructureMap.Graph.PluginGraph.FindInstance(System.Type, System.String)
0000000601c2dca0 00007fff6a716c1e StructureMap.BuildSession.CreateInstance(System.Type, System.String)
0000000601c2dcf0 00007fff6a716a4f StructureMap.Container.GetInstance[[System.__Canon, mscorlib]](System.String)
```

So you would suggest to change the `PluginGraph` to use `ConcurrentDictionary` rather than make the `LightweightCache` thread safe? Unfortunately I've no idea where else the `LightweightCache` could be used under multi-threading load, and looking for that places during production use is quite expensive ;)

**Comment by jeremydmiller** [comment]
@cspwizard You know your PR doesn't compile, right? So you didn't actually try this code out I assume?

**Comment by cspwizard** [comment]
Yeah, my bad. Missed the using during commit. 
However this should fix the issue. By the way it would be nicer from architectural point of view if you would use thread  safe structures by default, unless it's guaranteed to be single thread.

**Comment by jeremydmiller** [comment]
@cspwizard It would be nicer if you were compiling and running the unit tests before you submit a PR like a halfway competent software developer. It would also be nice if you knew more about the codebase and the cost of using thread safe collections when that's not necessary before making blanket statements like that.

**Comment by cspwizard** [comment]
I see the cost (and I guess the competence?) on dead servers, when the processes go in endless loop ;) I didn't say to use it everywhere, and I've no time for learning the SM codebase sorry.

**Comment by drusellers** [comment]
> I've no time for learning the SM codebase sorry.

@cspwizard this comment is a bit disheartening. If you don't have time to learn the code base, how can we be sure that you have even fixed the actual problem? How do we know that you haven't just moved the problem elsewhere?

That said, can you help me understand why this is needed? I understand its causing you an issue now in your codebase, but why does the rest of the community need it?

Do you have a small unit test that can reproduce this behavior? Ideally, we want to protect ourselves from these mistakes in the future as well.

**Comment by jeremydmiller** [comment]
As discussed earlier, I can't take this in. I might try to address this separately.

**Pull request closed without merging**
