### PR TITLE
Make Container.GetProfile thread-safe

### LINKED ISSUE #593: NullReferenceException on GetProfile
```
System.NullReferenceException: Object reference not set to an instance of an object.
   at StructureMap.Container.<>c.<CorrectSingletoneLifecycleForChild>b__45_0(Instance x)
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at StructureMap.StringExtensions.Each[T](IEnumerable`1 enumerable, Action`1 action)
   at StructureMap.Container.CorrectSingletoneLifecycleForChild(IPipelineGraph pipelineGraph)
   at StructureMap.Container.GetProfile(String profileName)
```
I don't have a repro yet - we restarted the services where it was happenning and it seemed to help.

### PR DESCRIPTION
**Pull request by DixonDs**
Fixes #593 . Using a lock might be not the most optimal way, but it is already used in `Configure` anyway.

### CODE REVIEW

**Comment by jeremydmiller** [comment]
@DixonDs I think you should be doing the locking inside of PipelineGraph itself, but do the double locking trick where you only lock if the profile being requested is missing. That should be a bit more efficient

**Comment by DixonDs** [comment]
@jeremydmiller I am not sure I understand you suggesion when you say "inside of PipelineGraph".

I think the issue is concurrency from 1) a read access from `Container.GetProfile` -> `CorrectSingletoneLifecycleForChild(pipeline)` -> ` var singletons = pipelineGraph.Instances.ImmediateInstances().Where(x => x.Lifecycle is SingletonLifecycle)` -> `ComplexInstanceGraph.ImmediateInstances` -> `PluginFamily.Instances` and 2) and a write access `Container.GetProfile` -> `new Container(pipeline)` -> `_pipelineGraph.RegisterContainer(this);` -> `_pluginGraph.Families[typeof (IContainer)].SetDefault(containerInstance);`

Probably that could be fixed by using `ConcurrentDictionary` for `PluginFamily._instances` but I think if `GetProfile` is the only issue, it is better to have some performance hit for not so often used `GetProfile` than on core `PluginFamily._instances`

In any case, I am more than happy if you provide a fix in whatever way - correctness comes before performance :) Feel free to close this PR in that case.

**Comment by henrik-m** [comment]
We just now stumbled upon this so we would be delighted if this or a similar PR could be merged asap. For us it manifested in the following exception:
```json
{
  "Message":"An error has occurred.",
  "ExceptionMessage":"Index was outside the bounds of the array.",
  "ExceptionType":"System.IndexOutOfRangeException",
  "StackTrace":"   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at StructureMap.Graph.PluginFamily.SetDefault(Instance instance)
   at StructureMap.Container..ctor(IPipelineGraph pipelineGraph)
   at StructureMap.Container.GetProfile(String profileName)[...]"
}
```

Is suppose it is because of this line in PluginFamily.SetDefault:
```csharp
_instances[instance.Name] = instance;
```
where ```_instances``` is an instance of LightweightCache which in turn is not implemented in a threadsafe manner.

**Comment by jeremydmiller** [comment]
@henrik-m I'm really not sure your problem is related to this PR, but I'd be happy to hear back what the outcome is when we pull this in.

@DixonDs I just meant that the locking should be happening inside of PipelineGraph where you can do more fine grained locking based on whether or not the item exists

**Comment by DixonDs** [comment]
@jeremydmiller do you think we can get this in and improve the performance later? Doing fine-grain locking in `PipelineGraph` without affecting overall performance is not straightforward, at least for me.

**Pull request merged**
