### PR TITLE
Add a test case for failing container configuration with contravariant generic types

### PR DESCRIPTION
**Pull request by jjanuszkiewicz**
I've added a set of tests which demonstrate a crash during container configuration when generic types with a contravariant type parameter are involved. Out of the 6 tests, only one fails (the `Register_generic_types_with_contravariance.configure_container_after_construction` one) - the remaining ones are for completness, to cover all cases (covariance, contravariance, no variance; container configuration during or after construction) and check if they work as expected.

This is for the issue we discussed on Gitter on Dec 23.

### CODE REVIEW

**Comment by jeremydmiller** [comment]
@jjanuszkiewicz In investigating this -- and for the very first time -- I'm going to blame the BCL itself. This unit test fails below:

```
            [Test]
            public void can_cast()
            {
                var bar = new GenericContravariantOfBar();

                bar.As<IGenericContravariant<Foo>>();

                // This fails
                typeof(IGenericContravariant<Foo>).IsAssignableFrom(typeof(GenericContravariantOfBar)).ShouldBeTrue();

                // So therefore, so does this
                typeof(GenericContravariantOfBar).CanBeCastTo<IGenericContravariant<Foo>>().ShouldBeTrue();
            }
```

I'm really not sure what to do with this. `IsAssignableFrom` is returning false, and that's what StructureMap depends on.

**Comment by khellang** [comment]
That's actually correct. If you have

```csharp
public class Foo { }

public class Bar : Foo { }

public interface IGenericContravariant<in T>
{
    void Method(T parameter);
}

public class GenericContravariantOfBar : IGenericContravariant<Bar>
{
    public void Method(Bar parameter) { }
}
```

You wouldn't be able to pass `Foo` to it, because `Bar` is *more* specific than `Foo`. So, you shouldn't be able to cast it to `IGenericContravariant<Foo>`.

**Comment by khellang** [comment]
Besides, the failing test is just trying to resolve
 - `IGenericContravariant<Foo>` -> `GenericContravariantOfFoo`
 - `IGenericContravariant<Bar>` -> `GenericContravariantOfBar`

Which both return `true` in an `IsAssignableFrom` check :smile:

**Comment by jjanuszkiewicz** [comment]
For what it's worth, this test passes on the twosix branch.

**Comment by jjanuszkiewicz** [comment]
Is there anything I can do to help with fixing this?

**Comment by jeremydmiller** [comment]
You could switch to registering all of this hierarchy as Lambda's where you build them yourself and cast them yourself to avoid this check. Otherwise, I think you'd need to build a new version of IsAssignableFrom() that works in this particular case, and I'm honestly not thrilled about that.

If 2.6 is working, it's because it's not doing as rigorous a check on the casting.

**Comment by khellang** [comment]
The problem is [this line right here](https://github.com/structuremap/structuremap/blob/3.1/src/StructureMap/Graph/CloseGenericFamilyPolicy.cs#L36). It returns the `IGenericContravariant<Foo>` family for the `IGenericContravariant<Bar>` request.

@jjanuszkiewicz Is this also a problem with v4? I see there's been some changes to the class, but the same line is still there... https://github.com/structuremap/structuremap/blob/master/src/StructureMap.Shared/Graph/CloseGenericFamilyPolicy.cs#L58-L60

**Comment by khellang** [comment]
Might've been https://github.com/structuremap/structuremap/commit/83552bd2670644294646204c2b2287989296ea19 that caused this :confused:

**Comment by khellang** [comment]
Also, if you swap the order in the registry, the test passes :stuck_out_tongue_closed_eyes: 

```diff
class TestRegistry : Registry
{
    public TestRegistry()
    {
-       For<IGenericContravariant<Foo>>().Use<GenericContravariantOfFoo>();
        For<IGenericContravariant<Bar>>().Use<GenericContravariantOfBar>();
+       For<IGenericContravariant<Foo>>().Use<GenericContravariantOfFoo>();
    }
}
```

**Comment by jjanuszkiewicz** [comment]
@jeremydmiller I'm not sure I get this, but please bear with me :smile: Isn't it the case that my way of registering those classes is actually correct (as proven by it working in the `configure_container_during_construction` test, where SM is able to register and resolve both interfaces correctly)? If it is able to register and resolve them in one case, there must be a "good" code path in there.

@khellang Yes, it is also a problem in v4 (tested on the current master).

Interesting find that the order matters here. Won't help me much, as I'm migrating a really large project from v2 to v3 and I'm not really in position to fix all the dozens of registries this way, let alone make the whole dev team register stuff in particular order in the future :smile:

I'll look for a way to avoid using the `.Configure()` method, but would really appreciate it if this could be fixed in SM itself.

**Comment by jeremydmiller** [comment]
@jjanuszkiewicz The first usage in the initial container construction doesn't have to run the assertion because the For<T>().Use<TConcrete>() signature forces the type conversion checks. In the Configure() case you're effectively merging a new configuration model into the original world and that's where the failing `assert` test fails for you on the call to IsAssignableFrom().

I can take a look at this again later today to see if we could bypass the assertion check in this case.

Is there any way you could upgrade to 4 instead of 3 though so I don't have to apply this twice?

**Comment by jjanuszkiewicz** [comment]
OK, I get it.

Sorry, no way for me to update directly to v4 yet - our code and many libraries unfortunately still rely a lot on `ObjectFactory`. The v2 to v3 update alone is already huge and I really can't make it so much larger. I'm whole heart for updating to v4 later this year, but we'll have to make it a separate step.

If this is a problem to apply a fix to official SMv3, I could get away with applying a patch to my fork of SM and releasing a private SM build to our internal nuget feed.

Thanks for spending your time looking at this!

**Comment by jjanuszkiewicz** [comment]
@khellang Thanks for pointing to the source line which causes this. This got me thinking and please take a look at this: this crash also happens in the *covariant* version, just change the order of registration there:

```
class TestRegistry : Registry
{
    public TestRegistry()
    {
-       For<IGenericCovariant<Foo>>().Use<GenericCovariantOfFoo>();
        For<IGenericCovariant<Bar>>().Use<GenericCovariantOfBar>();
+       For<IGenericCovariant<Foo>>().Use<GenericCovariantOfFoo>();
    }
}
```

What happens is that once the first plugin family is registered, it will be returned when checking the second registration. So to speak, if I understand the code correctly. Depending on whether co- or contra-variance is in play, you have to register the types in correct order (or, specifically, you have to register from the most derived to the least derived one to make it work; the variance changes which one, `Foo` or `Bar`, is more derived when used as a type parameter).

This has become a serious blocker for me now. Can I get your advice one this: since `CloseGenericFamilyPolicy` is new in v3 (right?) and I'm updating from v2, it should be safe for me to just disable this policy for the time being, as I should have no code relying on it? Does this make sense?

As for the fix, I think [the line in question](https://github.com/structuremap/structuremap/blob/3.1/src/StructureMap/Graph/CloseGenericFamilyPolicy.cs#L36) should have the sides of the `IsAssignableFrom` switched, i.e.

```
- return _graph.Families.ToArray().FirstOrDefault(x => type.GetTypeInfo().IsAssignableFrom(x.PluginType.GetTypeInfo()));
+ return _graph.Families.ToArray().FirstOrDefault(x => x.PluginType.GetTypeInfo().IsAssignableFrom(type.GetTypeInfo()));
```
depending on the variance kind in the resolved type's type parameters. I don't know how to determine which check to use, though. I also have no idea how this should work if the type has multiple type parameters with different variance kinds.

**Comment by jjanuszkiewicz** [comment]
I moved the commits to a dedicated PR branch and created a new PR #441.

Also, I added another test which demonstrates this incorrect behaviour, but with no variance involved.

**Pull request closed without merging**
